alias pvtool='Clinical.Patient.Client &'
alias sln='start *.sln'
alias go='explorer .'
alias subl='/C/"Program Files"/"Sublime Text 3"/sublime_text '
alias gr='grep -r '
alias gitk='gitk --all &'
alias reload='source ~/.bashrc'
